# Generated by Django 2.2.4 on 2019-10-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feel', models.TextField(blank=True, null=True)),
                ('look', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('smell', models.TextField(blank=True, null=True)),
                ('taste', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'beer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='input_beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=20)),
                ('second', models.CharField(max_length=20, null=True)),
                ('third', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'recommand_input_beer',
            },
        ),
    ]
